#!/usr/bin/env python3
"""Sumi Moji (variable): the same recipe scripts/build_latin.py uses for
the static faces — Source Code Pro VF as the base, Monaspace VF for the
punctuation/ligatures/one-cell arrows — but assembled as a CFF2 variable
font instead of twelve static instances. Two files come out, mirroring
Source Code Pro's own Upright/Italic split:

  dist/latin/SumiMoji[wght].otf         wght 200-900 (usWeightClass terms)
  dist/latin/SumiMoji-Italic[wght].otf  from SCP_VF_I, Monaspace slnt +
                                        the residual shear mona_transform
                                        already applies for the static
                                        Italic faces

Masters sit at the SCP VF's own master locations, read back from the CFF2
VarStore (build_latin.confirm_scp_master_wghts) — not assumed — plus the
Regular and Heavy positions (see the axis paragraph below). Monaspace
is bar-matched per master with erosion DISABLED (VFSource.matched
erode=False): erosion is a pathops boolean op on a fixed outline, not an
interpolatable deformation, so a VF master can't take that path (see
docs/sumi-moji-plan.md 段階2) — below SCP wght ≈366 Monaspace's punctuation
just stays at its own wght-200 floor instead, slightly heavier than the
bar-matched ideal. draw_clean's pathops.simplify pass is also disabled for
the same reason (overlap removal is not guaranteed point-compatible across
weights); masters keep overlapping contours, same as Adobe ships SCP's own
VF. No hinting, no subroutinizing: CFF2 VFs don't carry per-master hints
through fontTools's instancer, so static releases re-hint after
instancing (see build_latin.py), not here.

The wght axis is in usWeightClass terms, like the static faces' STAT:
user 300/350/400/500/700/900 = Light/Normal/Regular/Medium/Bold/Heavy,
default 400 = Regular (so OS/2 usWeightClass 400 matches the fvar
default, CSS `font-weight: 700` lands on OUR Bold, and a VF picked
without an axis value renders Regular, not the thinnest master). Each of
those user values maps (avar, generated by varLib from the designspace
axis map) to the SCP wght whose own '=' bar equals that Source Han Code
JP face's bar scaled 600/667 — the exact pairing build_latin.py's static
faces use, recomputed here as plain numbers instead of an instanced
font. The DESIGN coordinate the masters live on is SCP's own wght made
linear (scp_design_axis: its user wght pushed through SCP's fvar
normalization + avar, then stretched back onto 200..900), so that
straight-line interpolation between our masters reproduces SCP's
interpolation exactly — SCP's VF is NOT linear in its user wght (its
avar bends the axis, so e.g. user 300 sits only 27% of the way from the
200 master to the 400 master), and a VF that interpolated linearly in
SCP's user wght would put every intermediate weight in the wrong place
(the first cut of this script did: its Light was a 58u bar instead of
the static Light's 41u). The masters are SCP's own (read back from the
CFF2 VarStore, build_latin.confirm_scp_master_wghts) plus SCP instanced
at the Regular and Heavy positions — the Regular one is the default
master (a VF's default must be a master), the Heavy one is the axis
maximum (SCP's own 900 master sits above it, out of range; instancing
at Heavy is exact since SCP is linear between its 400 and 900 masters)
— and one at the Monaspace floor (mona_floor_wght: the SCP wght below
which Monaspace's bar-matching is clamped at its own wght 200), so the
clamped Monaspace outline is constant below it and tracks SCP above it.
STAT carries the same six user wght values as the static faces
(Regular elidable, linked to Bold) plus one 'ital' value per file (0
upright / 1 italic, upright linked to italic) — matching Source Code
Pro's own two-file STAT convention. MVAR/HVAR are excluded: nothing in
this recipe varies per-glyph metrics or advances by weight (advances are
fixed 600-multiples; OS/2 vertical metrics are measured once on the
default master and the same values are shared by every instance), so
there is no variation for either table to carry.

Usage:
  python scripts/build_latin_vf.py [upright|italic]   # default: both
Env (all required):
  SCP_VF_U, SCP_VF_I, MONA_VF, SHCJ_TTC   as for build_latin.py
Env (optional): SHOYU_VERSION
"""

import contextlib
import copy
import functools
import sys
from pathlib import Path

from fontTools.designspaceLib import (
    AxisDescriptor,
    DesignSpaceDocument,
    InstanceDescriptor,
    SourceDescriptor,
)
from fontTools.misc.roundTools import noRound
from fontTools.ttLib import TTFont
from fontTools.varLib import build as varlib_build
from fontTools.varLib import instancer
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.varLib.models import normalizeValue, piecewiseLinearMap

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build  # noqa: E402
import build_latin  # noqa: E402

CELL = build_latin.CELL     # 600, SCP's own advance
MONA_K = build_latin.MONA_K  # 600/1240
_, FAMILY, PS_FAMILY = build.LATIN_PROFILES["ship"]   # "Sumi Moji", "SumiMoji"

STYLES = {
    # style -> (env var for the SCP VF, italic bool, output filename)
    "upright": ("SCP_VF_U", False, f"{PS_FAMILY}[wght].otf"),
    "italic": ("SCP_VF_I", True, f"{PS_FAMILY}-Italic[wght].otf"),
}


def scp_source(scp_path):
    """The SCP VF as a build.VFSource: wght only, bars in SCP's own units
    (scale 1.0). Its matched() search is the one build_latin.py's static
    faces are placed by, so matched_wght() puts the VF's named instances
    exactly where the statics are."""
    return build._vf_source(scp_path, 1.0, {"wght": 0})


def weight_positions(scp, shcj_ttc_path, italic):
    """{weight name: SCP wght} for the six named weights build.FACES lists
    — the SCP wght whose own '=' bar equals SHCJ's bar x 600/667 for that
    face, exactly build_latin.py's static pairing (build_face looks up
    the SHCJ Italic face for an italic style, same here — SHCJ's italic
    faces do not measure the same bar as their upright counterparts).
    `scp` is a scp_source()."""
    factor = CELL / build.CELL   # 600/667
    return {weight: scp.matched_wght(build.shcj_bar_target(shcj_ttc_path, ref_name,
                                                           italic, factor))
            for weight, ref_name, _ in build.FACES}


def confirm_scp_master_wghts(vf):
    """The SCP VF's own wght master locations, read back from the CFF2
    VarStore's region peaks (on the wght axis) through avar/fvar rather
    than assumed — the variable Sumi Moji's masters go exactly where
    SCP's own are, so no interpolation error is introduced on the SCP
    side; only Monaspace needs matching per master.

    A region's PeakCoord is in POST-avar normalized space; forward-map a
    fine wght grid through fvar-normalize + avar and take, for each peak,
    the raw wght whose forward map lands closest to it. Always includes
    the axis default (peak 0.0, not itself stored as a region)."""
    axes = [a.axisTag for a in vf["fvar"].axes]
    wi = axes.index("wght")
    axis = vf["fvar"].axes[wi]
    avar = vf["avar"].segments.get("wght", {}) if "avar" in vf else {}
    cff2 = vf["CFF2"].cff
    td = cff2[cff2.fontNames[0]]
    peaks = sorted({round(r.VarRegionAxis[wi].PeakCoord, 6)
                    for r in td.VarStore.otVarStore.VarRegionList.Region} | {0.0})

    def forward(wght):
        lin = normalizeValue(wght, (axis.minValue, axis.defaultValue, axis.maxValue))
        return piecewiseLinearMap(lin, avar) if avar else lin

    grid = [(forward(w), w) for w in
            (axis.minValue + i * (axis.maxValue - axis.minValue) / 7000
             for i in range(7001))]
    return sorted({round(min(grid, key=lambda fw: abs(fw[0] - peak))[1])
                   for peak in peaks})


def scp_design_axis(vf):
    """SCP's wght axis as a LINEAR design coordinate: (design, breaks).

    design(user_wght) pushes SCP's user wght through its own fvar
    normalization and avar (the post-avar normalized value is what SCP's
    CFF2 VarStore regions are placed in, i.e. the space its masters
    interpolate linearly in) and stretches that back onto SCP's user
    range, so two SCP instances at design coordinates d1 and d2 blend by
    straight-line interpolation exactly as SCP itself would. Our masters
    are located in this coordinate (see module docstring). `breaks` are
    the SCP user wghts where its avar changes slope (plus min/default/
    max): every one of them has to be a breakpoint of OUR axis map too,
    or the composed user->design map would cut the corner."""
    axis = next(a for a in vf["fvar"].axes if a.axisTag == "wght")
    lo, dflt, hi = float(axis.minValue), float(axis.defaultValue), float(axis.maxValue)
    avar = vf["avar"].segments.get("wght", {}) if "avar" in vf else {}

    def denorm(n):
        return dflt + n * ((hi - dflt) if n >= 0 else (dflt - lo))

    def design(user):
        n = normalizeValue(user, (lo, dflt, hi))
        if avar:
            n = piecewiseLinearMap(n, avar)
        return denorm(n)

    breaks = sorted({lo, dflt, hi} | {denorm(k) for k in avar})
    return design, breaks


def user_axis(weight_pos, scp_design, scp_breaks, lo):
    """Our wght axis: (minimum, default, maximum, map, to_scp).

    User values are usWeightClass numbers (build.WEIGHT_CLASS: 300 Light
    ... 900 Heavy, default 400 Regular); `weight_pos` (weight_positions)
    gives the SCP user wght each of them stands for. to_scp(U) is that
    pairing made piecewise-linear (with the axis minimum `lo` pinned to
    SCP's own `lo`, so the range below Light stays available); the axis
    `map` is [(U, design)] through every breakpoint of to_scp AND every
    SCP avar break pulled back through to_scp, evaluated as
    scp_design(to_scp(U)) — the composition of two piecewise-linear maps
    is piecewise-linear on the union of their breakpoints, so the VF then
    reproduces SCP at EVERY U, not only at the six named weights."""
    pts = {float(lo): float(lo)}
    pts.update({float(build.WEIGHT_CLASS[w]): float(weight_pos[w])
                for w, _, _ in build.FACES})
    us = sorted(pts)
    for a, b in zip(us, us[1:]):
        if not pts[a] < pts[b]:
            raise RuntimeError(f"wght pairing is not monotonic: user {a}->{pts[a]}, "
                               f"user {b}->{pts[b]}")
    inv = {v: k for k, v in pts.items()}

    def to_scp(u):
        return piecewiseLinearMap(u, pts)

    breaks = set(us)
    for s in scp_breaks:
        if pts[us[0]] < s < pts[us[-1]]:
            breaks.add(piecewiseLinearMap(s, inv))
    mapping = [(u, scp_design(to_scp(u))) for u in sorted(breaks)]
    return us[0], float(build.WEIGHT_CLASS["Regular"]), us[-1], mapping, to_scp


def master_scp_wghts(scp_masters, to_scp, lo, default_u, hi_u, extra=()):
    """SCP user wghts to instance our masters at: the axis minimum, the
    Regular position (our default master) and the Heavy position (our
    axis maximum) first — their exact values are load-bearing — then
    SCP's own master locations and any `extra` positions (the Monaspace
    floor, see mona_floor_wght) inside the range, each dropped when it
    sits within 0.5 wght of a master already placed (two near-coincident
    masters would give varLib a near-singular model). Sorted."""
    top = to_scp(hi_u)
    ws = [float(lo), to_scp(default_u), top]
    for w in [float(w) for w in scp_masters] + [round(float(w), 2) for w in extra]:
        if lo < w < top and all(abs(w - x) > 0.5 for x in ws):
            ws.append(w)
    return sorted(ws)


def mona_floor_wght(scp, mona_source, slant):
    """The SCP wght at which Monaspace's bar-matching first hits its own
    wght floor (Monaspace wght 200's '=' bar, at our scale, equals SCP's
    bar there). A master goes here: below it every master carries the
    SAME clamped Monaspace outline (so interpolation stays constant, as
    the static faces' erode=False matching is), above it Monaspace
    tracks SCP's bar — without this master the VF would interpolate
    Monaspace linearly from the floor at wght 200 up to the 400 master,
    putting e.g. Normal's punctuation 4u too heavy. `scp` is a
    scp_source()."""
    return scp.matched_wght(mona_source.floor_bar(slant))


@contextlib.contextmanager
def unrounded_cff2_instancing():
    """fontTools' instancer rounds every instanced CFF2 charstring operand
    to an integer. Charstring operands are RELATIVE (rmoveto/rlineto/
    rrcurveto deltas), so those roundings accumulate along a path: an
    instance of 'm' can drift several units from SCP's own blend — and
    two instances drift differently, so a VF built from rounded masters
    reproduces SCP only AT its masters (10u off on 'm' between them,
    measured). With rounding off the masters keep SCP's exact blend
    (fixed 16.16 operands, a CFF2 charstring's native precision), and
    the VF interpolates it exactly. The static faces (build_latin.py)
    keep the default rounding: they are hinted and subroutinized as
    integer outlines, and their own drift is the same one every
    fontTools-instanced static carries."""
    orig = instancer.instantiateCFF2
    instancer.instantiateCFF2 = functools.partial(orig, round=noRound)
    try:
        yield
    finally:
        instancer.instantiateCFF2 = orig


def scp_base_at(vf, wght):
    """Static CID-keyed CFF master: SCP instanced at an EXACT wght (no bar
    search — VF masters sit at SCP's own confirmed locations) with
    unrounded outlines (unrounded_cff2_instancing), same CFF2->CFF +
    save/reload round trip as build_latin.static_base()."""
    inst = copy.deepcopy(vf)
    with unrounded_cff2_instancing():
        instantiateVariableFont(inst, {"wght": wght}, inplace=True)
    base = build_latin.static_base(inst)
    build_latin.fix_zone_order(base)
    return base


def graft_master(base, mona_source, slant):
    """Monaspace punctuation/ligatures onto one SCP master, in place —
    same helpers build_latin.py's static build_face uses, but bar-matched
    with erosion disabled (erode=False: a VF master can't take the
    non-interpolatable erosion path, see module docstring) while
    build.draw_clean runs with simplify=False (monkeypatched by the
    caller — every add_glyphs/replace_from_mona/add_missing_from_mona call
    below resolves `draw_clean` as build's own module global)."""
    target = build.bar_thickness(base, base.getBestCmap()[ord("=")])
    mona = mona_source.matched(target, slant, erode=False)
    dy = build.mona_baseline_shift(base, mona, MONA_K)
    alts = {}
    added = build.add_glyphs(base, mona, alts, build.LIGATURES, dy, cell=CELL)
    build.replace_from_mona(base, mona,
                            build.MONA_STANDALONE + build.MONA_AMBIGUOUS, dy, MONA_K)
    build_latin.add_missing_from_mona(base, mona, build.MONA_AMBIGUOUS, dy, MONA_K)
    build_latin.remap_scp_stylistic_sets(base)
    build.add_gsub(base, added, alts, build.LIGATURES)
    build.classify_unicode_marks(base)
    if "DSIG" in base:
        del base["DSIG"]
    return target, mona


def harmonize_feature_names(font):
    """fontTools.varLib.build requires every non-CFF2 table to be
    byte-identical across masters. Each per-weight SCP instance's own
    'name' table numbers its residual custom nameIDs (SCP's own cv/ss
    FeatureParams) DIFFERENTLY across independently-instanced wght
    locations — the instancer's per-location name-table subsetting does
    not preserve a stable numbering even when the underlying string is
    identical — and build.add_gsub's own name-ID allocation (_alloc_name_id)
    inherits that instability for the features we add on top. Fix:
    renumber every FeatureParams nameID canonically by the feature's
    POSITION in the FeatureList (already tag-sorted, so structurally
    identical across masters), rewriting a matching name record so the
    string travels with the new ID."""
    gsub = font["GSUB"].table
    name = font["name"]
    replaced = set()
    for i, fr in enumerate(gsub.FeatureList.FeatureRecord):
        params = fr.Feature.FeatureParams
        if params is None:
            continue
        for attr in ("UINameID", "FeatUILabelNameID"):
            nid = getattr(params, attr, None)
            if not nid:
                continue
            text = name.getDebugName(nid) or f"feature {fr.FeatureTag}"
            canon = 900 + i
            name.setName(text, canon, 3, 1, 0x409)
            setattr(params, attr, canon)
            if nid >= 256:
                replaced.add(nid)
    # the records the old IDs pointed at now hang from nothing (unless a
    # canonical ID happens to coincide): drop them, or 70-odd strings of
    # SCP's feature names ride along unreferenced
    still_used = {getattr(fr.Feature.FeatureParams, attr, None)
                  for fr in gsub.FeatureList.FeatureRecord if fr.Feature.FeatureParams
                  for attr in ("UINameID", "FeatUILabelNameID")}
    for nid in replaced - still_used:
        name.removeNames(nameID=nid)


def finalize_vf_names(vf, italic, version, credits, italic_angle):
    """Name table for the merged VF: build.set_names does the heavy
    lifting (credits, version, vendor, fsSelection/macStyle, post
    italicAngle/caret) exactly as for a static face with weight="Regular"
    (RIBBI: family "Sumi Moji", subfamily "Regular"/"Italic") — a VF file
    is not any one weight, so the weight-specific PostScript name
    set_names computes (SumiMoji-Regular / SumiMoji-RegularItalic) is
    wrong for it; overridden here to SumiMoji-Roman / SumiMoji-Italic
    (nameID 6) with a matching nameID 3 and nameID 25 (variations
    PostScript name prefix) "SumiMoji". nameID 16/17 are dropped:
    Source Code Pro's own VF omits them too — with fvar+STAT already
    describing the family, and nameID 1/2 here already being the plain
    RIBBI pair (no weight suffix at the file level), they are redundant
    (and varLib does not itself add them for a VF)."""
    build.set_names(vf, "", "Regular", italic, italic_angle,
                         version=version, credits=credits,
                         family_base=FAMILY, ps_base=PS_FAMILY, base_credit=None)
    new_ps = f"{PS_FAMILY}-{'Italic' if italic else 'Roman'}"
    name = vf["name"]
    new3 = name.getDebugName(3).rsplit(";", 1)[0] + ";" + new_ps   # set_names wrote it
    name.names = [n for n in name.names if n.nameID not in (3, 6, 16, 17)]
    for nid, val in ((3, new3), (6, new_ps), (25, PS_FAMILY)):
        name.setName(val, nid, 3, 1, 0x409)
    cff = vf["CFF2"].cff if "CFF2" in vf else vf["CFF "].cff
    if cff.fontNames:
        cff.fontNames[0] = new_ps
    return new_ps


def name_default_instance_by_font(vf):
    """fvar: the named instance sitting at the axis default (Regular /
    Italic) takes the FONT's own PostScript name (nameID 6, SumiMoji-Roman
    / SumiMoji-Italic) instead of a private 'SumiMoji-Regular' string —
    the fvar spec says the default instance's postScriptNameID must be 6
    or a record with the same value (fontbakery
    opentype/varfont/valid_default_instance_nameids); its subfamily name
    already equals nameID 2. The private record is dropped when nothing
    else refers to it."""
    fvar, name = vf["fvar"], vf["name"]
    default = {a.axisTag: a.defaultValue for a in fvar.axes}
    for inst in fvar.instances:
        if not all(abs(inst.coordinates.get(t, v) - v) < 1e-6 for t, v in default.items()):
            continue
        old = inst.postscriptNameID
        inst.postscriptNameID = 6
        if old not in (0xFFFF, 6) and not any(i.postscriptNameID == old
                                              for i in fvar.instances):
            name.removeNames(nameID=old)
        return
    raise RuntimeError("no named instance at the axis default")


def build_style(style, env, out_dir):
    env_key, italic, out_name = STYLES[style]
    scp_path = env[env_key]

    vf_meta = TTFont(scp_path)
    vf_meta.ensureDecompiled()
    scp_masters = confirm_scp_master_wghts(vf_meta)
    if len(scp_masters) != 3:
        raise RuntimeError(f"{style}: expected 3 SCP master locations, "
                           f"confirmed {scp_masters}")
    scp = scp_source(scp_path)
    axis = next(a for a in vf_meta["fvar"].axes if a.axisTag == "wght")
    if round(axis.defaultValue) not in scp_masters:
        raise RuntimeError(f"{style}: axis default {axis.defaultValue} is not "
                           f"one of the confirmed master locations {scp_masters}")
    print(f"[{style}] SCP master locations (confirmed from CFF2 VarStore): "
          f"{scp_masters}, axis {axis.minValue:.0f}-{axis.defaultValue:.0f}-"
          f"{axis.maxValue:.0f}")

    # 0. the axes: SCP's wght made linear (design), ours in usWeightClass
    #    terms (user) with the six SHCJ-bar-matched SCP wghts as the map's
    #    anchor points (see module docstring / scp_design_axis / user_axis)
    scp_design, scp_breaks = scp_design_axis(vf_meta)
    # rounded to 1/100 wght up front so the same number is the map's
    # anchor, the master's location and the instance position (an
    # unrounded 856.768 vs a rounded 856.77 master maps to user 900.001,
    # which varLib rejects as out of range)
    weight_pos = {w: round(v, 2) for w, v in
                  weight_positions(scp, env["SHCJ_TTC"], italic).items()}
    lo_u, default_u, hi_u, axis_map, to_scp = user_axis(
        weight_pos, scp_design, scp_breaks, axis.minValue)
    ref_angle = (vf_meta["post"].italicAngle or -12.0) if italic else None
    mona_source = build._vf_source(env["MONA_VF"], MONA_K,
                                   {"wght": 0, "wdth": 100, "slnt": 0})
    floor = mona_floor_wght(scp, mona_source, ref_angle)
    wghts = master_scp_wghts(scp_masters, to_scp, axis.minValue, default_u, hi_u,
                             extra=[floor])
    default_wght = round(to_scp(default_u), 2)
    print(f"[{style}] weights (user -> SCP wght): "
          f"{ {build.WEIGHT_CLASS[w]: round(v, 1) for w, v in weight_pos.items()} }; "
          f"Monaspace floor at SCP wght {floor:.1f}; masters at SCP wght {wghts} "
          f"(default {default_wght})")

    # 1. SCP-only bases, one per master (exact wght, no bar search —
    #    that's only needed to match Monaspace, below)
    bases = {w: scp_base_at(vf_meta, w) for w in wghts}

    # 2. Monaspace grafting: erode=False + simplify=False (see module
    #    docstring). draw_clean is monkeypatched only for the duration of
    #    this loop — every build.add_glyphs / replace_from_mona /
    #    add_missing_from_mona call below resolves the bare name
    #    `draw_clean` as build's own module global at call time.
    original_draw_clean = build.draw_clean
    build.draw_clean = lambda draws, pen: original_draw_clean(draws, pen, simplify=False)
    try:
        targets, monas = {}, {}
        for w in wghts:
            targets[w], monas[w] = graft_master(bases[w], mona_source, ref_angle)
    finally:
        build.draw_clean = original_draw_clean

    # 3. glyph order must match across masters for varLib.build to merge
    #    the CFF2 charstrings at all
    order = bases[wghts[0]].getGlyphOrder()
    for w in wghts[1:]:
        if bases[w].getGlyphOrder() != order:
            raise RuntimeError(f"{style}: glyph order diverged at wght {w}")

    # 4. harmonize GSUB FeatureParams nameIDs across masters (see
    #    harmonize_feature_names) and update each master's own bbox
    #    (grafted Monaspace content can extend past SCP's own bbox)
    for w in wghts:
        harmonize_feature_names(bases[w])
        build.update_bbox(bases[w])
    win_ascent = max(b["head"].yMax for b in bases.values())
    win_descent = max(-b["head"].yMin for b in bases.values())

    # credits come off the default master's own (still SCP-inherited) name
    # table — finalize_vf_names below replaces it
    credits = build_latin.credits_from(bases[default_wght], monas[default_wght])

    # 5. designspace: in-memory sources (no masters written to disk) at
    #    their SCP-linear design coordinate, the user axis map (varLib
    #    turns it into avar), 6 named instances at the usWeightClass
    #    user values (designspace instance locations are DESIGN
    #    coordinates; varLib maps them back through the axis map for fvar)
    doc = DesignSpaceDocument()
    axis_d = AxisDescriptor()
    axis_d.tag = axis_d.name = "wght"
    axis_d.minimum = lo_u
    axis_d.default = default_u
    axis_d.maximum = hi_u
    axis_d.map = axis_map
    axis_d.labelNames = {"en": "Weight"}
    doc.addAxis(axis_d)
    for w in wghts:
        src = SourceDescriptor()
        src.name = f"{style}-{w}"
        src.path = f"<memory:{style}-{w}>"
        src.font = bases[w]
        src.location = {"wght": scp_design(w)}
        if w == default_wght:
            src.copyLib = src.copyInfo = src.copyGroups = src.copyFeatures = True
        doc.addSource(src)

    for weight, _, _ in build.FACES:
        inst = InstanceDescriptor()
        inst.location = {"wght": scp_design(to_scp(build.WEIGHT_CLASS[weight]))}
        inst.styleName = (f"{weight} Italic".replace("Regular Italic", "Italic")
                          if italic else weight)
        inst.postScriptFontName = f"{PS_FAMILY}-{weight}{'Italic' if italic else ''}"
        doc.addInstance(inst)

    # STAT built by hand afterward (build_stat); MVAR/HVAR excluded --
    # nothing in this recipe varies OS/2 metrics or advances by weight
    vf, _model, _masters = varlib_build(doc, exclude=["MVAR", "HVAR", "STAT"])
    if "avar" not in vf:
        raise RuntimeError(f"{style}: varLib produced no avar from the axis map")

    # 6. finishing touches, once, on the merged VF (measured on the
    #    default master: varLib.build builds the VF on the default source's
    #    own tables; MVAR/HVAR excluded, nothing varies them)
    build.set_monospace_metadata(vf)
    build.set_latin_heights(vf)
    build_latin.use_typo_metrics(vf)
    build_latin.fit_win_metrics(vf, ascent=win_ascent, descent=win_descent)
    vf["OS/2"].recalcUnicodeRanges(vf)
    build.recalc_codepage_range(vf)
    ps = finalize_vf_names(vf, italic, env.get("SHOYU_VERSION"), credits,
                           ref_angle if ref_angle is not None else -12.0)
    # STAT: every weight (Regular elidable, linked to Bold) plus this
    # file's ital value — Source Code Pro's own two-file STAT convention
    build.add_stat(vf, [w for w, _, _ in build.FACES], italic)
    name_default_instance_by_font(vf)
    # head: update_bbox measures the DEFAULT instance (a CFF2 glyph set
    # draws at the default); the VF's box is the union over the masters
    build.update_bbox(vf)
    head = vf["head"]
    head.xMin = min(b["head"].xMin for b in bases.values())
    head.yMin = min(b["head"].yMin for b in bases.values())
    head.xMax = max(b["head"].xMax for b in bases.values())
    head.yMax = max(b["head"].yMax for b in bases.values())

    out_path = Path(out_dir) / out_name
    out_path.parent.mkdir(parents=True, exist_ok=True)
    vf.save(out_path)
    return (f"{style}: masters at SCP wght {wghts}, user wght "
            f"{ {build.WEIGHT_CLASS[w]: round(v, 1) for w, v in weight_pos.items()} }, "
            f"ps={ps} glyphs={vf['maxp'].numGlyphs} -> "
            f"{out_path.relative_to(out_dir)}")


def main():
    only = sys.argv[1] if len(sys.argv) > 1 else None
    if only and only not in STYLES:
        sys.exit(f"unknown style {only!r} (want {list(STYLES)})")
    env = build.env_paths(dict.fromkeys(build_latin.VF_ENV))
    out_dir = build.ROOT / "dist" / "latin"
    styles = [only] if only else list(STYLES)
    for style in styles:
        print(build_style(style, env, str(out_dir)))


if __name__ == "__main__":
    main()
